# Generated by Django 5.2.1 on 2025-05-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mmr',
            field=models.IntegerField(default=0),
        ),
    ]
