
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: tala_trivia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tala_trivia_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: tala_trivia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
    networks:
      - tala_trivia_network


volumes:
  postgres_data:

networks:
  tala_trivia_network:
    driver: bridge